version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /opt/es/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /opt/es/data/:/usr/share/elasticsearch/data:rw
      - /etc/localhost:/etc/localhost:ro
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
  collector:
    image: sxp/apm-collector:5.0
    container_name: collector
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 10800:10800
      - 11800:11800
      - 12800:12800
  webapp:
    image: sxp/apm-webapp:5.0
    container_name: webapp
    depends_on:
      - collector
    links:
      - collector
    restart: always
    ports:
      - 8080:8080
    environment:
      collector.ribbon.listOfServers: collector:12800